"""Input/output helpers for MD-MAIA tables and grids."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def write_table(df: pd.DataFrame, path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix.lower() == ".parquet":
        df.to_parquet(path, index=False)
    else:
        df.to_csv(path, index=False)


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path)


def write_dx(
    grid: np.ndarray,
    origin: np.ndarray,
    spacing: float,
    path: str | Path,
    object_name: str = "density",
) -> None:
    """Write a simple OpenDX scalar grid."""

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    nx, ny, nz = grid.shape
    ox, oy, oz = origin
    with path.open("w") as handle:
        handle.write(f"# {object_name}\n")
        handle.write(f"object 1 class gridpositions counts {nx} {ny} {nz}\n")
        handle.write(f"origin {ox:.6f} {oy:.6f} {oz:.6f}\n")
        handle.write(f"delta {spacing:.6f} 0 0\n")
        handle.write(f"delta 0 {spacing:.6f} 0\n")
        handle.write(f"delta 0 0 {spacing:.6f}\n")
        handle.write(f"object 2 class gridconnections counts {nx} {ny} {nz}\n")
        handle.write(f"object 3 class array type double rank 0 items {grid.size} data follows\n")
        flat = grid.ravel(order="C")
        for i in range(0, flat.size, 3):
            handle.write(" ".join(f"{x:.8e}" for x in flat[i : i + 3]) + "\n")
        handle.write('attribute "dep" string "positions"\n')
        handle.write('object "density" class field\n')
        handle.write('component "positions" value 1\n')
        handle.write('component "connections" value 2\n')
        handle.write('component "data" value 3\n')


def write_cube(
    grid: np.ndarray,
    origin: np.ndarray,
    spacing: float,
    path: str | Path,
    comment: str = "MD-MAIA density",
) -> None:
    """Write a Gaussian cube scalar grid.

    Coordinates are assumed to be in Angstrom and are converted to Bohr for the
    cube header. The file contains one dummy atom at the local-frame origin.
    """

    bohr_per_angstrom = 1.0 / 0.529177210903
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    nx, ny, nz = grid.shape
    origin_bohr = np.asarray(origin, dtype=float) * bohr_per_angstrom
    spacing_bohr = spacing * bohr_per_angstrom

    with path.open("w") as handle:
        handle.write(f"{comment}\n")
        handle.write("Generated by MD-MAIA\n")
        handle.write(
            f"{1:5d}{origin_bohr[0]:12.6f}{origin_bohr[1]:12.6f}{origin_bohr[2]:12.6f}\n"
        )
        handle.write(f"{nx:5d}{spacing_bohr:12.6f}{0.0:12.6f}{0.0:12.6f}\n")
        handle.write(f"{ny:5d}{0.0:12.6f}{spacing_bohr:12.6f}{0.0:12.6f}\n")
        handle.write(f"{nz:5d}{0.0:12.6f}{0.0:12.6f}{spacing_bohr:12.6f}\n")
        handle.write(f"{0:5d}{0.0:12.6f}{0.0:12.6f}{0.0:12.6f}{0.0:12.6f}\n")
        flat = grid.ravel(order="C")
        for i in range(0, flat.size, 6):
            handle.write("".join(f"{x:13.5e}" for x in flat[i : i + 6]) + "\n")
